### ISSUE TITLE
Install fails due to error in Cro::HTTP::Router

### ISSUE THREAD

**Issue by Xliff** [croservices/cro-http#71] opened 2019-03-05 04:35 UTC
Error message follows:

```
No such method 'e' for invocant of type 'Slip'
  in sub static-resource at /home/cbwood/Projects/cro-http/lib/Cro/HTTP/Router.pm6 (Cro::HTTP::Router) line 1064
  in block  at t/http-router.t line 1938
  in block  at /home/cbwood/Projects/cro-http/lib/Cro/HTTP/Router.pm6 (Cro::HTTP::Router) line 130=
```

**Comment by Altai-man** [comment] 2019-03-05 04:50
I wonder if this is a regression...
I'll look today into it.

**Comment by Xliff** [comment] 2019-03-05 04:51
Thanks. I  am attempting to debug it further. I will post here with any new information.

And...

```
$perl6 --version
This is Rakudo version 2018.12-321-g845433b47 built on MoarVM version 2018.12-117-gdcafbc4c7
implementing Perl 6.d.
```

**Comment by Xliff** [comment] 2019-03-05 04:57
After applying this patch:

```
diff --git a/lib/Cro/HTTP/Router.pm6 b/lib/Cro/HTTP/Router.pm6
index 23dcd93..0d1c249 100644
--- a/lib/Cro/HTTP/Router.pm6
+++ b/lib/Cro/HTTP/Router.pm6
@@ -1061,7 +1061,8 @@ module Cro::HTTP::Router {
             return ($path ~~ m/ '.' ( <-[ \. ]>+ ) $ / )[0].Str;
         }
 
-        if $path and my $resource = %?RESOURCES{$path} and $resource.IO.e and !$resource.IO.d {
+        say "R: { %?RESOURCES{$path}.gist }";
+        if $path and (my $resource = %?RESOURCES{$path}).elems and $resource.IO.e and !$resource.IO.d {
             content get-mime(get-extension($path)), slurp($resource, :bin);
         } else {
             for @indexes {
```

We are now down to the following error, that occurs in t/http-router.t:#1970 :

```perl6
$req = Cro::HTTP::Request.new(method => 'GET', target => '/folder-indexes');
    $source.emit($req);
    given $responses.receive -> $r {
        like body-text($r), rx{ 'this is a test' \n }, 'indexes in a folder of %*RESOURCES';
        is $r.status, 200, 'Good status';
    }
```

**Comment by Altai-man** [comment] 2019-03-06 13:10
Can confirm failing on `2018.12-302-g121ca5fda`.

**Comment by Altai-man** [comment] 2019-03-06 14:50
I am building 2018.12 to see if it will work with it.
```
➜  cro-http git:(master) ✗ perl6 -Ilib t/http-router.t
"/home/koto/Work/cro/cro-http/resources/index.html".IO
(Resource)
ok 1 - Get index.html from %*RESOURCES
ok 2 - Static-resource sets correct status code
"/home/koto/Work/cro/cro-http/resources/folder".IO
(Resource)
ok 3 - indexes in a folder of %*RESOURCES
ok 4 - Good status
1..4
➜  cro-http git:(master) ✗ 
```

This is a rakudo regression.

**Comment by Altai-man** [comment] 2019-03-06 16:05
So this is not a bug, but rather a fix of the bug.

The API was written by @ufobat, maybe we can re-imagine it somehow considering that directory-access is now prohibited?

**Comment by ufobat** [comment] 2019-03-07 09:27
I have added the else part just for symmetry reasons. I think removing the else branch and adding @xliff patch would fix that issue.
I am just sad that there is no introspection of %? RESOURCES, but that would only be part of that ticket if you want to keep the symmetry to the filesystem-acces-thingy of Cro::HTTP::Router.

**Comment by ufobat** [comment] 2019-03-07 09:29
FYI https://github.com/rakudo/rakudo/issues/2547

**Comment by Altai-man** [comment] 2019-03-07 14:07
Should be fixed now, waiting for travis.

**Comment by Altai-man** [comment] 2019-03-07 14:25
Passes on latest now, so closing.
https://travis-ci.org/croservices/cro-http/jobs/503118327

**Closed by Altai-man** 2019-03-07 14:25 UTC

**Comment by Xliff** [comment] 2019-03-07 15:06
Still failing on my end.

```
ok 401 - Good status
No such method 'e' for invocant of type 'Slip'
  in sub static-resource at /home/cbwood/Projects/cro-http/lib/Cro/HTTP/Router.pm6 (Cro::HTTP::Router) line 1064
  in block  at t/http-router.t line 1938
  in block  at /home/cbwood/Projects/cro-http/lib/Cro/HTTP/Router.pm6 (Cro::HTTP::Router) line 130

not ok 402 - indexes in a folder of %*RESOURCES
# Failed test 'indexes in a folder of %*RESOURCES'
# at t/http-router.t line 1973
# expected a match with: rx{ 'this is a test' \n }
#                   got: ""
not ok 403 - Good status
# Failed test 'Good status'
# at t/http-router.t line 1974
# expected: '200'
#      got: '500'
```

```
$ perl6 --version
This is Rakudo version 2018.12-341-g1ec4f171d built on MoarVM version 2018.12-117-gdcafbc4c7
implementing Perl 6.d.
```

**Comment by Altai-man** [comment] 2019-03-07 15:31
Can you try on latest rakudo master? Travis just used it and passed the tests fine.

**Comment by Xliff** [comment] 2019-03-07 16:09
That was a tested on a freshly compiled rakudo before I submitted it. Are you aware of a later version?

**Comment by Altai-man** [comment] 2019-03-08 07:02
Hmm, that's odd. Testing on 2019.03.

**Comment by Xliff** [comment] 2019-03-08 07:04
I will grab a clean copy and re-test.

**Comment by Altai-man** [comment] 2019-03-08 07:16
D'oh.
Tests are failing on 2019.03.
How the travis is alive then? That's a mystery.

**Comment by Altai-man** [comment] 2019-03-08 07:31
What if we index resources with https://github.com/croservices/cro-http/commit/70ccf18b89a12271d0d8e0995f065a61e4dc769c ? It passes `zef test .` on
`This is Rakudo version 2019.03 built on MoarVM version 2019.03` for me.

**Comment by Altai-man** [comment] 2019-03-08 07:45
Travis is ok (https://travis-ci.org/croservices/cro-http/jobs/503478923) for `2019.03-22-g70d61b214`.

**Comment by Xliff** [comment] 2019-03-08 08:50
D'oh! I forgot to merge upstream/master. Tests are now passing!

Sorry for the delay.
