### ISSUE TITLE
Repeatable HTTP 2 issue

### ISSUE THREAD

**Issue by lizmat** [croservices/cro-http#156] opened 2021-09-24 13:57 UTC
Run this and get the error below.  Add `:http<1.1>` to the client init, and the problem goes away.

````raku
use Cro::HTTP::Client;

my $client := Cro::HTTP::Client.new:
  user-agent => 'Ecosystem::Archive 0.0.1';

my $resp := await $client.get:
  'https://raw.githubusercontent.com/Raku/ecosystem/master/META.list';
my $text := await $resp.body;

for $text.lines -> $URL {
    say $URL;
    my $resp := await $client.get($URL);
    my $text := await $resp.body;
    say $text;
last if $++ == 5;
}
````

**Comment by lizmat** [comment] 2021-09-24 13:58
````
$ raku --ll-exception foo.raku
https://raw.githubusercontent.com/khalidelboray/Pastebin-Pasteee/main/META6.json
Header table index 82 out of range
   at SETTING::src/core.c/Exception.pm6:62  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:throw)
 from SETTING::src/core.c/control.pm6:221  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:die)
 from SETTING::src/core.c/control.pm6:209  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:die)
 from site#sources/4CC285A8AB160824E5A42DC6EF776B610FCEB2F9 (HTTP::HPACK):258  (/Users/liz/.raku/precomp/0C92196409C455833E38D43F062D9B0809D2F3F9/4C/4CC285A8AB160824E5A42DC6EF776B610FCEB2F9:)
 from site#sources/4CC285A8AB160824E5A42DC6EF776B610FCEB2F9 (HTTP::HPACK):252  (/Users/liz/.raku/precomp/0C92196409C455833E38D43F062D9B0809D2F3F9/4C/4CC285A8AB160824E5A42DC6EF776B610FCEB2F9:resolve-decoded-index)
 from site#sources/4CC285A8AB160824E5A42DC6EF776B610FCEB2F9 (HTTP::HPACK):286  (/Users/liz/.raku/precomp/0C92196409C455833E38D43F062D9B0809D2F3F9/4C/4CC285A8AB160824E5A42DC6EF776B610FCEB2F9:)
 from site#sources/4CC285A8AB160824E5A42DC6EF776B610FCEB2F9 (HTTP::HPACK):285  (/Users/liz/.raku/precomp/0C92196409C455833E38D43F062D9B0809D2F3F9/4C/4CC285A8AB160824E5A42DC6EF776B610FCEB2F9:)
 from site#sources/4CC285A8AB160824E5A42DC6EF776B610FCEB2F9 (HTTP::HPACK):282  (/Users/liz/.raku/precomp/0C92196409C455833E38D43F062D9B0809D2F3F9/4C/4CC285A8AB160824E5A42DC6EF776B610FCEB2F9:decode-headers)
 from site#sources/43241E93E97E663878983BC698B481BA0B8A589E (Cro::HTTP2::GeneralParser):187  (/Users/liz/.raku/precomp/0C92196409C455833E38D43F062D9B0809D2F3F9/43/43241E93E97E663878983BC698B481BA0B8A589E:set-headers)
 from site#sources/43241E93E97E663878983BC698B481BA0B8A589E (Cro::HTTP2::GeneralParser):101  (/Users/liz/.raku/precomp/0C92196409C455833E38D43F062D9B0809D2F3F9/43/43241E93E97E663878983BC698B481BA0B8A589E:)
 from site#sources/43241E93E97E663878983BC698B481BA0B8A589E (Cro::HTTP2::GeneralParser):72  (/Users/liz/.raku/precomp/0C92196409C455833E38D43F062D9B0809D2F3F9/43/43241E93E97E663878983BC698B481BA0B8A589E:)
 from SETTING::src/core.c/Rakudo/Supply.pm6:250  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Lock/Async.pm6:176  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:run-with-updated-recursion-list)
 from SETTING::src/core.c/Lock/Async.pm6:142  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:protect-or-queue-on-recursion)
 from SETTING::src/core.c/Rakudo/Supply.pm6:256  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:run-supply-code)
 from SETTING::src/core.c/Rakudo/Supply.pm6:184  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Rakudo/Supply.pm6:325  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:run-emit)
 from <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/control.pm6:198  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:emit)
 from site#sources/974DA281FE5E567A236C783A12F334663018B5A6 (Cro::HTTP2::FrameParser):93  (/Users/liz/.raku/precomp/0C92196409C455833E38D43F062D9B0809D2F3F9/97/974DA281FE5E567A236C783A12F334663018B5A6:)
 from site#sources/974DA281FE5E567A236C783A12F334663018B5A6 (Cro::HTTP2::FrameParser):62  (/Users/liz/.raku/precomp/0C92196409C455833E38D43F062D9B0809D2F3F9/97/974DA281FE5E567A236C783A12F334663018B5A6:)
 from site#sources/974DA281FE5E567A236C783A12F334663018B5A6 (Cro::HTTP2::FrameParser):61  (/Users/liz/.raku/precomp/0C92196409C455833E38D43F062D9B0809D2F3F9/97/974DA281FE5E567A236C783A12F334663018B5A6:)
 from site#sources/974DA281FE5E567A236C783A12F334663018B5A6 (Cro::HTTP2::FrameParser):41  (/Users/liz/.raku/precomp/0C92196409C455833E38D43F062D9B0809D2F3F9/97/974DA281FE5E567A236C783A12F334663018B5A6:)
 from SETTING::src/core.c/Rakudo/Supply.pm6:446  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Rakudo/Supply.pm6:445  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:run-supply-code)
 from SETTING::src/core.c/Rakudo/Supply.pm6:408  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Rakudo/Supply.pm6:126  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:run-emit)
 from <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/control.pm6:198  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:emit)
 from site#sources/8F9CE57B4C9E54F00938F862E837CA40DCD18536 (Cro::TLS):92  (/Users/liz/.raku/precomp/0C92196409C455833E38D43F062D9B0809D2F3F9/8F/8F9CE57B4C9E54F00938F862E837CA40DCD18536:)
 from SETTING::src/core.c/Rakudo/Supply.pm6:250  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Lock/Async.pm6:176  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:run-with-updated-recursion-list)
 from SETTING::src/core.c/Lock/Async.pm6:142  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:protect-or-queue-on-recursion)
 from SETTING::src/core.c/Rakudo/Supply.pm6:256  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:run-supply-code)
 from SETTING::src/core.c/Rakudo/Supply.pm6:184  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Rakudo/Supply.pm6:126  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:run-emit)
 from <unknown>:1  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/control.pm6:198  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:emit)
 from SETTING::src/core.c/Channel.pm6:136  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Rakudo/Supply.pm6:250  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Lock/Async.pm6:176  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:run-with-updated-recursion-list)
 from SETTING::src/core.c/Lock/Async.pm6:142  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:protect-or-queue-on-recursion)
 from SETTING::src/core.c/Rakudo/Supply.pm6:256  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:run-supply-code)
 from SETTING::src/core.c/Rakudo/Supply.pm6:184  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Supply-factories.pm6:303  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:245  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:244  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:239  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:run-one)
 from SETTING::src/core.c/ThreadPoolScheduler.pm6:281  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:)
 from SETTING::src/core.c/Thread.pm6:54  (/Users/liz/Github/rakudo.moar/install/share/perl6/runtime/CORE.c.setting.moarvm:THREAD-ENTRY)
````

**Comment by patrickbkr** [comment] 2023-02-26 12:51
This is a duplicate of https://github.com/croservices/cro-http/issues/122

**Closed** 2023-04-12 15:48 UTC
